# Blog settings
permalink: /blog/:title


# My variables
name: Kai Iyer
description: Thoughts, Ideas and musings
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

theme: jekyll-theme-midnight