# Blog settings
permalink: /blog/:title


# My variables
name: Kai Iyer
description: A blog for the folks who will break the limits of Privacy and Inforamation Security.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass

links:
  # Link to YouTube.
  youtube: https://youtube.com/thecodingtrain/

  # Link to Patreon.
  patreon: https://patreon.com/kaiiyer

  # Link to Discord
  discord: https://discord.gg/hPuGy2g

  # Link to the merch store.
  twitter: https://twitter.com/kaiiyer
  
  # Link to the Amazon store.
amazon: https://www.amazon.com/shop/thecodingtrain

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

theme: jekyll-theme-midnight
